# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:03
from __future__ import unicode_literals

from django.db import migrations
import iasf.apply.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0020_auto_20171112_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='activities_extracurriculars',
        ),
        migrations.RemoveField(
            model_name='application',
            name='activities_other',
        ),
        migrations.RemoveField(
            model_name='application',
            name='activities_workexperience',
        ),
        migrations.AlterField(
            model_name='application',
            name='activities',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, null=True, verbose_name='Academic awards / honors / Athletics / Clubs / Extracurriculars / Work Experience / Other'),
        ),
    ]
