# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import iasf.apply.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0023_auto_20171113_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='finaid_scholarships_hope',
        ),
        migrations.RemoveField(
            model_name='application',
            name='finaid_scholarships_pell',
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_hope_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='HOPE Annual Amount'),
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_hope_duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='HOPE Expected Duration'),
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_hope_eligible',
            field=models.NullBooleanField(verbose_name='Eligible for HOPE Scholarship?'),
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_pell_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Pell Annual Amount'),
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_pell_duration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pell Expected Duration'),
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_scholarships_pell_eligible',
            field=models.NullBooleanField(verbose_name='Eligible for HOPE Scholarship?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='college_received_acceptance_letter',
            field=models.NullBooleanField(verbose_name='I have received an acceptance letter.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_scholarships_other',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, null=True, verbose_name='Financial assistance from other sources'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
    ]
