# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0024_auto_20171116_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationInProgress',
            fields=[
                ('application_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apply.Application')),
            ],
            bases=('apply.application',),
        ),
    ]
