# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0015_auto_20171105_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='file_finaid_additional',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Any additional documents (optional)'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_finaid_cost',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Financial aid package / cost of attendance letter from the university'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_finaid_cssprofile',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='CSS profile report'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_finaid_taxreturn',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='2016 tax return; 1040 along with supporting documentation'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_finaid_tuition',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Tuition bill for applicant / other dependents if necessary'),
        ),
        migrations.AddField(
            model_name='application',
            name='file_transcript',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Please upload your high school transcript.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_act_scores',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Please upload ACT scores if applicable.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_resume',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Please upload your resume if available.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_sat_scores',
            field=models.FileField(blank=True, null=True, upload_to=b'', verbose_name='Please upload SAT scores if applicable.'),
        ),
    ]
