# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0017_auto_20171112_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='financial_needs_statement',
            new_name='finaid_needs_statement',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='scholarships_hope',
            new_name='finaid_scholarships_hope',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='scholarships_other',
            new_name='finaid_scholarships_other',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='scholarships_pell',
            new_name='finaid_scholarships_pell',
        ),
        migrations.AddField(
            model_name='application',
            name='finaid_applying_for',
            field=models.NullBooleanField(help_text='If you are applying for financial aid, you will be applying for the separate financial aid scholarship. Otherwise, you will be considered only for the merit scholarship.', verbose_name='Applying for financial aid?'),
        ),
        migrations.AddField(
            model_name='application',
            name='signature',
            field=models.CharField(blank=True, max_length=101, null=True, verbose_name='Signature'),
        ),
    ]
