# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0019_auto_20171112_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='activities_awards',
            new_name='activities',
        ),
        migrations.AlterField(
            model_name='application',
            name='home_address_1',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_address_2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_city',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_state',
            field=models.CharField(blank=True, default='GA', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_gpa',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='HS GPA (100 or 4.0 scale)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_act_composite',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT Score - composite'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_act_math',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT Score - math'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_act_reading',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT Score - reading'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_act_science',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT Score - science'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_act_writing',
            field=models.IntegerField(blank=True, null=True, verbose_name='ACT Score - writing'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_sat_math',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAT Score - math'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_sat_reading',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAT Score - reading'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_sat_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAT Score - total'),
        ),
        migrations.AlterField(
            model_name='application',
            name='scores_sat_writing',
            field=models.IntegerField(blank=True, null=True, verbose_name='SAT Score - writing'),
        ),
    ]
