# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import iasf.apply.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0021_auto_20171112_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='activities',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, help_text='Please list your main extracurricular activities and work experience below: Include the grade level of your participation. Feel free to attach a resume or a more complete list (on the upload documents page) to supplement this list.', null=True, verbose_name='Activities'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_income_parent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total income of both parents/ guardians last year'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_income_student',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total income of student / applicant last year'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_list_dependents',
            field=iasf.apply.fields.JSONListSchemaField(blank=True, null=True, verbose_name='List of dependents currently attending college'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_needs_statement',
            field=models.TextField(blank=True, null=True, verbose_name='Please describe any unusual financial circumstances in your family not listed previously on your application. You may include any information that will be beneficial to the Indian American Scholarship committee.'),
        ),
    ]
