# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0026_auto_20171116_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationinprogress',
            name='application_ptr',
        ),
        migrations.DeleteModel(
            name='ApplicationInProgress',
        ),
    ]
