# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import iasf.apply.fields
import iasf.apply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0027_auto_20171120_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_last_modified',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='claim_indian_descent',
            field=models.IntegerField(choices=[(1, 'Maternal grandparents'), (2, 'Paternal grandparents')], null=True, verbose_name='Claim to Indian descent'),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay',
            field=models.TextField(null=True, validators=[iasf.apply.validators.MaxWordsValidator(500)], verbose_name='Essay (500 words max)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_act_scores',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Please upload ACT scores if applicable.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_finaid_additional',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Any additional documents (optional)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_finaid_cost',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Financial aid package / cost of attendance letter from the university'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_finaid_cssprofile',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='CSS profile report'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_finaid_taxreturn',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='2016 tax return; 1040 along with supporting documentation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_finaid_tuition',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Tuition bill for applicant / other dependents if necessary'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_resume',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Please upload your resume if available.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_sat_scores',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Please upload SAT scores if applicable.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_transcript',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Please upload your high school transcript.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='finaid_applying_for',
            field=models.BooleanField(default=0, help_text='If you are applying for financial aid, you will be applying for the separate financial aid scholarship. Otherwise, you will be considered only for the merit scholarship.', verbose_name='Applying for financial aid?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='home_address_1',
            field=models.CharField(max_length=128, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_city',
            field=models.CharField(default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_state',
            field=models.CharField(default='GA', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='application',
            name='home_zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_address_1',
            field=models.CharField(max_length=128, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_city',
            field=models.CharField(default='', max_length=64, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_class_rank',
            field=models.IntegerField(blank=True, null=True, verbose_name='HS Class Rank'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_class_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='HS Class Size'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_counselor_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_counselor_first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Counselor first name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_counselor_last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_counselor_middle_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_name',
            field=models.CharField(max_length=100, verbose_name='HS Name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_state',
            field=models.CharField(default='GA', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='application',
            name='hs_zip_code',
            field=models.CharField(default='', max_length=5, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='parent_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
