# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 22:38
from __future__ import unicode_literals

from django.db import migrations, models
import iasf.apply.fields
import iasf.apply.validators


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0028_auto_20171222_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='where_heard',
            field=models.IntegerField(choices=[(1, 'Friend/Family'), (2, 'Guidance counselor'), (3, 'Khabar magazine'), (4, 'Internet search'), (5, 'Other')], null=True, verbose_name='Where did you hear about the IASF scholarship program?'),
        ),
        migrations.AlterField(
            model_name='application',
            name='essay',
            field=models.TextField(help_text="Tell us something, like a personal experience, that's not evident from your application. This is an opportunity to show us who you are.", null=True, validators=[iasf.apply.validators.MaxWordsValidator(500)], verbose_name='Essay (500 words max)'),
        ),
        migrations.AlterField(
            model_name='application',
            name='file_transcript',
            field=iasf.apply.fields.DocumentField(blank=True, content_types=['application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/pdf', 'image/png', 'image/jpeg', 'image/gif'], help_text='Additionally, please send either a sealed paper copy to Rajesh Kurup (2137 Wisteria Way Atlanta GA 30317) or email an electronic copy from your guidance counselor to info@iasf.org.', max_upload_size=10485760, mime_lookup_length=4096, null=True, upload_to='', verbose_name='Please upload your high school transcript.'),
        ),
    ]
