# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0029_auto_20180204_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='file_resume',
        ),
    ]
