# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0030_remove_application_file_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='submitted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='signature',
            field=models.CharField(blank=True, help_text='', max_length=101, null=True, verbose_name='Signature'),
        ),
    ]
