# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-23 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0032_auto_20180205_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='signature',
            field=models.CharField(blank=True, help_text='', max_length=101, null=True, verbose_name='Signature'),
        ),
    ]
